# Generated by Django 2.2.4 on 2019-12-11 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='documents', verbose_name='Файл')),
                ('description', models.CharField(max_length=400, verbose_name='Краткое описание')),
                ('private', models.BooleanField(null=True, verbose_name='Приватный ?')),
                ('score', models.IntegerField(default=0, null=True, verbose_name='рейтинг')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ':Документы',
                'verbose_name_plural': 'Документ',
            },
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(null=True, verbose_name='-1/1')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
